import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

async function main() {
    console.log("🌱 Starting database seed...")

    // Clear existing data (optional - comment out if you want to keep existing data)
    // await prisma.machine.deleteMany({})
    // await prisma.customHiringCentre.deleteMany({})
    // await prisma.operator.deleteMany({})

    // 1. Create Custom Hiring Centres
    console.log("📍 Creating Custom Hiring Centres...")
    const chcs = await prisma.customHiringCentre.createMany({
        data: [
            {
                id: "chc-001",
                name: "Haryana CHC Center - Hisar",
                latitude: 29.1833,
                longitude: 75.7597,
                district: "Hisar",
                state: "Haryana",
                contact_number: "+91-9876543210",
                email: "hisar@chc.com",
                owner_name: "Rajesh Kumar",
                total_machines: 0,
                performance_rating: 4.5,
                revenue_this_month: 150000,
            },
            {
                id: "chc-002",
                name: "Punjab CHC Center - Ludhiana",
                latitude: 30.9046,
                longitude: 75.8569,
                district: "Ludhiana",
                state: "Punjab",
                contact_number: "+91-9876543211",
                email: "ludhiana@chc.com",
                owner_name: "Priya Singh",
                total_machines: 0,
                performance_rating: 4.8,
                revenue_this_month: 200000,
            },
            {
                id: "chc-003",
                name: "UP CHC Center - Agra",
                latitude: 27.1767,
                longitude: 78.0081,
                district: "Agra",
                state: "Uttar Pradesh",
                contact_number: "+91-9876543212",
                email: "agra@chc.com",
                owner_name: "Amit Patel",
                total_machines: 0,
                performance_rating: 4.2,
                revenue_this_month: 120000,
            },
            {
                id: "chc-004",
                name: "MP CHC Center - Indore",
                latitude: 22.7196,
                longitude: 75.8577,
                district: "Indore",
                state: "Madhya Pradesh",
                contact_number: "+91-9876543213",
                email: "indore@chc.com",
                owner_name: "Vikram Verma",
                total_machines: 0,
                performance_rating: 4.6,
                revenue_this_month: 175000,
            },
            {
                id: "chc-005",
                name: "Rajasthan CHC Center - Jaipur",
                latitude: 26.9046,
                longitude: 75.8569,
                district: "Jaipur",
                state: "Rajasthan",
                contact_number: "+91-9876543214",
                email: "jaipur@chc.com",
                owner_name: "Devendra Singh",
                total_machines: 0,
                performance_rating: 4.4,
                revenue_this_month: 165000,
            },
            {
                id: "chc-006",
                name: "Karnataka CHC Center - Bengaluru",
                latitude: 12.9716,
                longitude: 77.5946,
                district: "Bengaluru",
                state: "Karnataka",
                contact_number: "+91-9876543215",
                email: "bengaluru@chc.com",
                owner_name: "Suresh Rao",
                total_machines: 0,
                performance_rating: 4.7,
                revenue_this_month: 220000,
            },
            {
                id: "chc-007",
                name: "Tamil Nadu CHC Center - Chennai",
                latitude: 13.0827,
                longitude: 80.2707,
                district: "Chennai",
                state: "Tamil Nadu",
                contact_number: "+91-9876543216",
                email: "chennai@chc.com",
                owner_name: "Ramakrishnan S",
                total_machines: 0,
                performance_rating: 4.3,
                revenue_this_month: 140000,
            },
            {
                id: "chc-008",
                name: "Gujarat CHC Center - Ahmedabad",
                latitude: 23.0225,
                longitude: 72.5714,
                district: "Ahmedabad",
                state: "Gujarat",
                contact_number: "+91-9876543217",
                email: "ahmedabad@chc.com",
                owner_name: "Jayesh Patel",
                total_machines: 0,
                performance_rating: 4.9,
                revenue_this_month: 250000,
            },
        ],
        skipDuplicates: true,
    })
    console.log(`✅ Created ${chcs.count} CHCs`)

    // 2. Create Operators
    console.log("👤 Creating Operators...")
    const operators = await prisma.operator.createMany({
        data: [
            {
                id: "op-001",
                name: "Harpreet Singh",
                phone: "9876543210",
                chc_id: "chc-001",
                rating: 4.8,
                total_hours_worked: 480,
            },
            {
                id: "op-002",
                name: "Ajay Kumar",
                phone: "9876543211",
                chc_id: "chc-001",
                rating: 4.5,
                total_hours_worked: 360,
            },
            {
                id: "op-003",
                name: "Priya Sharma",
                phone: "9876543212",
                chc_id: "chc-002",
                rating: 4.9,
                total_hours_worked: 520,
            },
            {
                id: "op-004",
                name: "Rajesh Patel",
                phone: "9876543213",
                chc_id: "chc-002",
                rating: 4.6,
                total_hours_worked: 420,
            },
            {
                id: "op-005",
                name: "Vikram Singh",
                phone: "9876543214",
                chc_id: "chc-003",
                rating: 4.3,
                total_hours_worked: 380,
            },
            {
                id: "op-006",
                name: "Neha Verma",
                phone: "9876543215",
                chc_id: "chc-003",
                rating: 4.7,
                total_hours_worked: 450,
            },
            {
                id: "op-007",
                name: "Rohit Gupta",
                phone: "9876543216",
                chc_id: "chc-004",
                rating: 4.4,
                total_hours_worked: 400,
            },
            {
                id: "op-008",
                name: "Sneha Desai",
                phone: "9876543217",
                chc_id: "chc-005",
                rating: 4.6,
                total_hours_worked: 470,
            },
            {
                id: "op-009",
                name: "Deepak Reddy",
                phone: "9876543218",
                chc_id: "chc-006",
                rating: 4.5,
                total_hours_worked: 510,
            },
            {
                id: "op-010",
                name: "Anita Nair",
                phone: "9876543219",
                chc_id: "chc-006",
                rating: 4.8,
                total_hours_worked: 490,
            },
            {
                id: "op-011",
                name: "Suresh Kumar",
                phone: "9876543220",
                chc_id: "chc-007",
                rating: 4.7,
                total_hours_worked: 540,
            },
            {
                id: "op-012",
                name: "Lakshmi S",
                phone: "9876543221",
                chc_id: "chc-007",
                rating: 4.6,
                total_hours_worked: 410,
            },
            {
                id: "op-013",
                name: "Nikhil Deshmukh",
                phone: "9876543222",
                chc_id: "chc-008",
                rating: 4.9,
                total_hours_worked: 550,
            },
            {
                id: "op-014",
                name: "Kavya Nambiar",
                phone: "9876543223",
                chc_id: "chc-008",
                rating: 4.8,
                total_hours_worked: 480,
            },
            {
                id: "op-015",
                name: "Manish Verma",
                phone: "9876543224",
                chc_id: "chc-001",
                rating: 4.4,
                total_hours_worked: 370,
            },
            {
                id: "op-016",
                name: "Priyanka Singh",
                phone: "9876543225",
                chc_id: "chc-002",
                rating: 4.7,
                total_hours_worked: 430,
            },
        ],
        skipDuplicates: true,
    })
    console.log(`✅ Created ${operators.count} Operators`)

    // 3. Create Machines
    console.log("🚜 Creating Machines...")
    const machines = await prisma.machine.createMany({
        data: [
            {
                id: "M-001",
                registration_number: "DL-01-AB-1234",
                machine_type: "baler",
                chc_id: "chc-001",
                status: "active",
                latitude: 29.1833,
                longitude: 75.7597,
                district: "Hisar",
                state: "Haryana",
                total_hours: 480,
                fuel_efficiency: 8.5,
                utilization_rate: 85,
                fuel_level: 75,
                operator_id: "op-001",
                make: "John Deere",
                model: "Round Baler",
                year: 2022,
            },
            {
                id: "M-002",
                registration_number: "PB-02-CD-5678",
                machine_type: "seeder",
                chc_id: "chc-001",
                status: "idle",
                latitude: 29.2,
                longitude: 75.8,
                district: "Hisar",
                state: "Haryana",
                total_hours: 320,
                fuel_efficiency: 7.2,
                utilization_rate: 65,
                fuel_level: 45,
                operator_id: "op-002",
                make: "Mahindra",
                model: "Precision Seeder",
                year: 2021,
            },
            {
                id: "M-003",
                registration_number: "PB-03-EF-9012",
                machine_type: "harvester",
                chc_id: "chc-002",
                status: "active",
                latitude: 30.9046,
                longitude: 75.8569,
                district: "Ludhiana",
                state: "Punjab",
                total_hours: 520,
                fuel_efficiency: 6.8,
                utilization_rate: 92,
                fuel_level: 90,
                operator_id: "op-003",
                make: "CLAAS",
                model: "Combine Harvester",
                year: 2023,
            },
            {
                id: "M-004",
                registration_number: "UP-04-GH-3456",
                machine_type: "mulcher",
                chc_id: "chc-003",
                status: "maintenance",
                latitude: 27.1767,
                longitude: 78.0081,
                district: "Agra",
                state: "Uttar Pradesh",
                total_hours: 380,
                fuel_efficiency: 7.9,
                utilization_rate: 70,
                fuel_level: 30,
                operator_id: "op-005",
                make: "Kuhn",
                model: "Disc Mulcher",
                year: 2020,
            },
            {
                id: "M-005",
                registration_number: "MP-05-IJ-7890",
                machine_type: "tiller",
                chc_id: "chc-004",
                status: "active",
                latitude: 22.7196,
                longitude: 75.8577,
                district: "Indore",
                state: "Madhya Pradesh",
                total_hours: 420,
                fuel_efficiency: 9.1,
                utilization_rate: 78,
                fuel_level: 65,
                operator_id: "op-007",
                make: "Eicher",
                model: "Power Tiller",
                year: 2022,
            },
            {
                id: "M-006",
                registration_number: "RJ-06-KL-2345",
                machine_type: "happy_seeder",
                chc_id: "chc-005",
                status: "active",
                latitude: 26.9046,
                longitude: 75.8569,
                district: "Jaipur",
                state: "Rajasthan",
                total_hours: 470,
                fuel_efficiency: 8.3,
                utilization_rate: 82,
                fuel_level: 55,
                operator_id: "op-008",
                make: "Stihl",
                model: "Happy Seeder Pro",
                year: 2023,
            },
            {
                id: "M-007",
                registration_number: "HR-07-MN-6789",
                machine_type: "zero_till_drill",
                chc_id: "chc-001",
                status: "offline",
                latitude: 29.15,
                longitude: 75.75,
                district: "Hisar",
                state: "Haryana",
                total_hours: 250,
                fuel_efficiency: 8.0,
                utilization_rate: 45,
                fuel_level: 20,
                operator_id: null,
                make: "Shatil",
                model: "Zero Till Drill",
                year: 2021,
            },
            {
                id: "M-008",
                registration_number: "PB-08-OP-0123",
                machine_type: "baler",
                chc_id: "chc-002",
                status: "active",
                latitude: 30.95,
                longitude: 75.9,
                district: "Ludhiana",
                state: "Punjab",
                total_hours: 550,
                fuel_efficiency: 8.2,
                utilization_rate: 88,
                fuel_level: 80,
                operator_id: "op-004",
                make: "Krone",
                model: "Round Baler X",
                year: 2023,
            },
            {
                id: "M-009",
                registration_number: "KA-09-QR-4567",
                machine_type: "harvester",
                chc_id: "chc-006",
                status: "active",
                latitude: 12.9716,
                longitude: 77.5946,
                district: "Bengaluru",
                state: "Karnataka",
                total_hours: 610,
                fuel_efficiency: 7.1,
                utilization_rate: 94,
                fuel_level: 85,
                operator_id: "op-009",
                make: "Fendt",
                model: "Combine Pro",
                year: 2023,
            },
            {
                id: "M-010",
                registration_number: "TN-10-ST-8901",
                machine_type: "seeder",
                chc_id: "chc-007",
                status: "active",
                latitude: 13.0827,
                longitude: 80.2707,
                district: "Chennai",
                state: "Tamil Nadu",
                total_hours: 480,
                fuel_efficiency: 8.4,
                utilization_rate: 81,
                fuel_level: 60,
                operator_id: "op-011",
                make: "Pricton",
                model: "Seed Drill",
                year: 2022,
            },
            {
                id: "M-011",
                registration_number: "GJ-11-UV-2345",
                machine_type: "tiller",
                chc_id: "chc-008",
                status: "active",
                latitude: 23.0225,
                longitude: 72.5714,
                district: "Ahmedabad",
                state: "Gujarat",
                total_hours: 520,
                fuel_efficiency: 8.9,
                utilization_rate: 89,
                fuel_level: 75,
                operator_id: "op-013",
                make: "Swaraj",
                model: "Power Tiller Pro",
                year: 2023,
            },
            {
                id: "M-012",
                registration_number: "HR-12-WX-6789",
                machine_type: "mulcher",
                chc_id: "chc-001",
                status: "idle",
                latitude: 29.1,
                longitude: 75.7,
                district: "Hisar",
                state: "Haryana",
                total_hours: 290,
                fuel_efficiency: 7.5,
                utilization_rate: 55,
                fuel_level: 40,
                operator_id: "op-015",
                make: "Kubota",
                model: "Mulch Master",
                year: 2021,
            },
            {
                id: "M-013",
                registration_number: "PB-13-YZ-0234",
                machine_type: "happy_seeder",
                chc_id: "chc-002",
                status: "active",
                latitude: 30.92,
                longitude: 75.88,
                district: "Ludhiana",
                state: "Punjab",
                total_hours: 440,
                fuel_efficiency: 8.6,
                utilization_rate: 86,
                fuel_level: 70,
                operator_id: "op-016",
                make: "Agrotech",
                model: "Happy Seeder Plus",
                year: 2023,
            },
            {
                id: "M-014",
                registration_number: "KA-14-AB-5678",
                machine_type: "baler",
                chc_id: "chc-006",
                status: "active",
                latitude: 12.98,
                longitude: 77.6,
                district: "Bengaluru",
                state: "Karnataka",
                total_hours: 580,
                fuel_efficiency: 8.1,
                utilization_rate: 87,
                fuel_level: 68,
                operator_id: "op-010",
                make: "Massey Ferguson",
                model: "Baler 2000",
                year: 2022,
            },
            {
                id: "M-015",
                registration_number: "TN-15-CD-9012",
                machine_type: "zero_till_drill",
                chc_id: "chc-007",
                status: "active",
                latitude: 13.05,
                longitude: 80.3,
                district: "Chennai",
                state: "Tamil Nadu",
                total_hours: 390,
                fuel_efficiency: 8.2,
                utilization_rate: 75,
                fuel_level: 50,
                operator_id: "op-012",
                make: "Shatil",
                model: "Zero Till Pro",
                year: 2022,
            },
            {
                id: "M-016",
                registration_number: "GJ-16-EF-3456",
                machine_type: "harvester",
                chc_id: "chc-008",
                status: "active",
                latitude: 23.05,
                longitude: 72.58,
                district: "Ahmedabad",
                state: "Gujarat",
                total_hours: 600,
                fuel_efficiency: 6.9,
                utilization_rate: 91,
                fuel_level: 88,
                operator_id: "op-014",
                make: "New Holland",
                model: "Combine 8000",
                year: 2023,
            },
        ],
        skipDuplicates: true,
    })
    console.log(`✅ Created ${machines.count} Machines`)

    // 4. Create Usage Logs (Bookings)
    console.log("📋 Creating Usage Logs...")
    const now = new Date()
    const usageLogs = await prisma.usageLog.createMany({
        data: [
            {
                id: "ul-001",
                machine_id: "M-001",
                operator_id: "op-001",
                start_time: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000),
                end_time: new Date(now.getTime() - 6.5 * 24 * 60 * 60 * 1000),
                latitude: 29.1833,
                longitude: 75.7597,
                district: "Hisar",
                state: "Haryana",
                area_covered: 25.5,
                fuel_consumed: 8.3,
                farmer_name: "Ramesh Kumar",
                farmer_contact: "9876543290",
                village: "Haryana Village",
                notes: "Baling completed successfully",
            },
            {
                id: "ul-002",
                machine_id: "M-003",
                operator_id: "op-003",
                start_time: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000),
                end_time: new Date(now.getTime() - 4.5 * 24 * 60 * 60 * 1000),
                latitude: 30.9046,
                longitude: 75.8569,
                district: "Ludhiana",
                state: "Punjab",
                area_covered: 45.0,
                fuel_consumed: 15.2,
                farmer_name: "Harpreet Singh",
                farmer_contact: "9876543291",
                village: "Punjab Village",
                notes: "Harvesting done on time",
            },
            {
                id: "ul-003",
                machine_id: "M-002",
                operator_id: "op-002",
                start_time: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
                end_time: new Date(now.getTime() - 2.5 * 24 * 60 * 60 * 1000),
                latitude: 29.2,
                longitude: 75.8,
                district: "Hisar",
                state: "Haryana",
                area_covered: 32.0,
                fuel_consumed: 9.5,
                farmer_name: "Suresh Patel",
                farmer_contact: "9876543292",
                village: "Hisar Village",
                notes: "Seeding operation successful",
            },
            {
                id: "ul-004",
                machine_id: "M-005",
                operator_id: "op-007",
                start_time: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
                end_time: new Date(now.getTime() - 1.5 * 24 * 60 * 60 * 1000),
                latitude: 22.7196,
                longitude: 75.8577,
                district: "Indore",
                state: "Madhya Pradesh",
                area_covered: 18.5,
                fuel_consumed: 6.2,
                farmer_name: "Vikram Desai",
                farmer_contact: "9876543293",
                village: "MP Village",
                notes: "Tilling completed",
            },
            {
                id: "ul-005",
                machine_id: "M-006",
                operator_id: "op-008",
                start_time: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000),
                end_time: new Date(now.getTime() - 0.5 * 24 * 60 * 60 * 1000),
                latitude: 26.9046,
                longitude: 75.8569,
                district: "Jaipur",
                state: "Rajasthan",
                area_covered: 28.0,
                fuel_consumed: 7.8,
                farmer_name: "Arjun Singh",
                farmer_contact: "9876543294",
                village: "Rajasthan Village",
                notes: "Happy seeding done",
            },
            {
                id: "ul-006",
                machine_id: "M-009",
                operator_id: "op-009",
                start_time: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000),
                end_time: new Date(now.getTime() - 7.5 * 24 * 60 * 60 * 1000),
                latitude: 12.9716,
                longitude: 77.5946,
                district: "Bengaluru",
                state: "Karnataka",
                area_covered: 38.5,
                fuel_consumed: 14.2,
                farmer_name: "Vijay Kumar",
                farmer_contact: "9876543295",
                village: "Karnataka Village",
                notes: "Harvesting in progress",
            },
            {
                id: "ul-007",
                machine_id: "M-010",
                operator_id: "op-011",
                start_time: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000),
                end_time: new Date(now.getTime() - 5.5 * 24 * 60 * 60 * 1000),
                latitude: 13.0827,
                longitude: 80.2707,
                district: "Chennai",
                state: "Tamil Nadu",
                area_covered: 29.5,
                fuel_consumed: 10.1,
                farmer_name: "Ravi Prakash",
                farmer_contact: "9876543296",
                village: "Tamil Nadu Village",
                notes: "Seeding completed successfully",
            },
            {
                id: "ul-008",
                machine_id: "M-011",
                operator_id: "op-013",
                start_time: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000),
                end_time: new Date(now.getTime() - 3.5 * 24 * 60 * 60 * 1000),
                latitude: 23.0225,
                longitude: 72.5714,
                district: "Ahmedabad",
                state: "Gujarat",
                area_covered: 35.0,
                fuel_consumed: 11.8,
                farmer_name: "Amar Patel",
                farmer_contact: "9876543297",
                village: "Gujarat Village",
                notes: "Tilling operation finished",
            },
            {
                id: "ul-009",
                machine_id: "M-004",
                operator_id: "op-005",
                start_time: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000),
                end_time: new Date(now.getTime() - 8.5 * 24 * 60 * 60 * 1000),
                latitude: 27.1767,
                longitude: 78.0081,
                district: "Agra",
                state: "Uttar Pradesh",
                area_covered: 20.0,
                fuel_consumed: 6.9,
                farmer_name: "Suresh Gupta",
                farmer_contact: "9876543298",
                village: "UP Village",
                notes: "Mulching done",
            },
            {
                id: "ul-010",
                machine_id: "M-013",
                operator_id: "op-016",
                start_time: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
                end_time: new Date(now.getTime() - 2.5 * 24 * 60 * 60 * 1000),
                latitude: 30.92,
                longitude: 75.88,
                district: "Ludhiana",
                state: "Punjab",
                area_covered: 33.0,
                fuel_consumed: 12.5,
                farmer_name: "Vikram Rao",
                farmer_contact: "9876543299",
                village: "Punjab Village 2",
                notes: "Happy seeding operation",
            },
            {
                id: "ul-011",
                machine_id: "M-014",
                operator_id: "op-010",
                start_time: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000),
                end_time: new Date(now.getTime() - 9.5 * 24 * 60 * 60 * 1000),
                latitude: 12.98,
                longitude: 77.6,
                district: "Bengaluru",
                state: "Karnataka",
                area_covered: 42.0,
                fuel_consumed: 16.3,
                farmer_name: "Naveen Kumar",
                farmer_contact: "9876543300",
                village: "Karnataka Village 2",
                notes: "Baling completed",
            },
            {
                id: "ul-012",
                machine_id: "M-015",
                operator_id: "op-012",
                start_time: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000),
                end_time: new Date(now.getTime() - 6.5 * 24 * 60 * 60 * 1000),
                latitude: 13.05,
                longitude: 80.3,
                district: "Chennai",
                state: "Tamil Nadu",
                area_covered: 31.0,
                fuel_consumed: 11.2,
                farmer_name: "Deepak Nambiar",
                farmer_contact: "9876543301",
                village: "Tamil Nadu Village 2",
                notes: "Zero till drilling",
            },
            {
                id: "ul-013",
                machine_id: "M-016",
                operator_id: "op-014",
                start_time: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000),
                end_time: new Date(now.getTime() - 4.5 * 24 * 60 * 60 * 1000),
                latitude: 23.05,
                longitude: 72.58,
                district: "Ahmedabad",
                state: "Gujarat",
                area_covered: 44.5,
                fuel_consumed: 17.0,
                farmer_name: "Ashok Deshmukh",
                farmer_contact: "9876543302",
                village: "Gujarat Village 2",
                notes: "Harvesting ongoing",
            },
        ],
        skipDuplicates: true,
    })
    console.log(`✅ Created ${usageLogs.count} Usage Logs`)

    // 5. Create Maintenance Records
    console.log("🔧 Creating Maintenance Records...")
    const maintenanceRecords = await prisma.maintenanceRecord.createMany({
        data: [
            {
                id: "mr-001",
                machine_id: "M-001",
                service_type: "oil_change",
                service_date: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000),
                next_due_date: new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000),
                cost: 1500,
                description: "Oil and filter changed",
                technician: "Mohan Singh",
                parts_replaced: ["oil", "filter"],
            },
            {
                id: "mr-002",
                machine_id: "M-003",
                service_type: "filter_replacement",
                service_date: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000),
                next_due_date: new Date(now.getTime() + 45 * 24 * 60 * 60 * 1000),
                cost: 800,
                description: "Air filter replaced",
                technician: "Rajesh Verma",
                parts_replaced: ["air_filter"],
            },
            {
                id: "mr-003",
                machine_id: "M-004",
                service_type: "general_maintenance",
                service_date: new Date(now.getTime() - 45 * 24 * 60 * 60 * 1000),
                next_due_date: new Date(now.getTime() + 15 * 24 * 60 * 60 * 1000),
                cost: 3500,
                description: "Full machine inspection and maintenance",
                technician: "Pradeep Kumar",
                parts_replaced: ["belt", "spark_plug", "brake_pad"],
            },
            {
                id: "mr-004",
                machine_id: "M-005",
                service_type: "wheel_alignment",
                service_date: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000),
                next_due_date: new Date(now.getTime() + 80 * 24 * 60 * 60 * 1000),
                cost: 2500,
                description: "Wheel alignment and balancing",
                technician: "Sudhir Singh",
                parts_replaced: [],
            },
            {
                id: "mr-005",
                machine_id: "M-002",
                service_type: "repair",
                service_date: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000),
                next_due_date: new Date(now.getTime() + 60 * 24 * 60 * 60 * 1000),
                cost: 2000,
                description: "Engine repair",
                technician: "Anil Patel",
                parts_replaced: ["fuel_pump", "nozzles"],
            },
            {
                id: "mr-006",
                machine_id: "M-006",
                service_type: "oil_change",
                service_date: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000),
                next_due_date: new Date(now.getTime() + 40 * 24 * 60 * 60 * 1000),
                cost: 1800,
                description: "Oil change and filter service",
                technician: "Vikram Sharma",
                parts_replaced: ["oil", "filter"],
            },
            {
                id: "mr-007",
                machine_id: "M-009",
                service_type: "general_maintenance",
                service_date: new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000),
                next_due_date: new Date(now.getTime() + 5 * 24 * 60 * 60 * 1000),
                cost: 4500,
                description: "Complete overhaul and inspection",
                technician: "Ramesh Kumar",
                parts_replaced: ["belt", "spark_plug", "fuel_filter", "hydraulic_oil"],
            },
            {
                id: "mr-008",
                machine_id: "M-010",
                service_type: "filter_replacement",
                service_date: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000),
                next_due_date: new Date(now.getTime() + 35 * 24 * 60 * 60 * 1000),
                cost: 950,
                description: "Fuel and air filter replacement",
                technician: "Govind Singh",
                parts_replaced: ["fuel_filter", "air_filter"],
            },
            {
                id: "mr-009",
                machine_id: "M-011",
                service_type: "wheel_alignment",
                service_date: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000),
                next_due_date: new Date(now.getTime() + 88 * 24 * 60 * 60 * 1000),
                cost: 3000,
                description: "Wheel balancing and alignment",
                technician: "Surender Yadav",
                parts_replaced: [],
            },
            {
                id: "mr-010",
                machine_id: "M-012",
                service_type: "repair",
                service_date: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000),
                next_due_date: new Date(now.getTime() + 75 * 24 * 60 * 60 * 1000),
                cost: 2800,
                description: "Hydraulic system repair",
                technician: "Nitin Desai",
                parts_replaced: ["hydraulic_cylinder", "seals"],
            },
            {
                id: "mr-011",
                machine_id: "M-013",
                service_type: "oil_change",
                service_date: new Date(now.getTime() - 35 * 24 * 60 * 60 * 1000),
                next_due_date: new Date(now.getTime() + 25 * 24 * 60 * 60 * 1000),
                cost: 1600,
                description: "Oil and coolant service",
                technician: "Pradeep Nair",
                parts_replaced: ["oil", "coolant"],
            },
            {
                id: "mr-012",
                machine_id: "M-014",
                service_type: "general_maintenance",
                service_date: new Date(now.getTime() - 50 * 24 * 60 * 60 * 1000),
                next_due_date: new Date(now.getTime() + 10 * 24 * 60 * 60 * 1000),
                cost: 5000,
                description: "Full machine inspection and preventive maintenance",
                technician: "Ashok Reddy",
                parts_replaced: ["spark_plugs", "battery", "brake_pads", "air_filter"],
            },
            {
                id: "mr-013",
                machine_id: "M-015",
                service_type: "filter_replacement",
                service_date: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000),
                next_due_date: new Date(now.getTime() + 42 * 24 * 60 * 60 * 1000),
                cost: 1100,
                description: "Oil and air filter service",
                technician: "Lakshmi Verma",
                parts_replaced: ["oil_filter", "air_filter"],
            },
            {
                id: "mr-014",
                machine_id: "M-016",
                service_type: "repair",
                service_date: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
                next_due_date: new Date(now.getTime() + 70 * 24 * 60 * 60 * 1000),
                cost: 3200,
                description: "Engine timing and valve adjustment",
                technician: "Sanjay Patel",
                parts_replaced: ["timing_belt", "valve_gaskets"],
            },
        ],
        skipDuplicates: true,
    })
    console.log(`✅ Created ${maintenanceRecords.count} Maintenance Records`)

    // 6. Create Alerts
    console.log("⚠️ Creating Alerts...")
    const alerts = await prisma.alert.createMany({
        data: [
            {
                id: "alert-001",
                machine_id: "M-001",
                chc_id: "chc-001",
                alert_type: "underutilization",
                severity: "medium",
                status: "open",
                message: "Machine underutilization below 80%",
                description: "M-001 utilization rate is 85%, close to threshold",
            },
            {
                id: "alert-002",
                machine_id: "M-004",
                chc_id: "chc-003",
                alert_type: "maintenance",
                severity: "high",
                status: "open",
                message: "Maintenance due soon",
                description: "M-004 maintenance is overdue by 10 days",
            },
            {
                id: "alert-003",
                machine_id: "M-007",
                chc_id: "chc-001",
                alert_type: "offline",
                severity: "critical",
                status: "open",
                message: "Machine offline",
                description: "M-007 has not been used for 25 days",
            },
            {
                id: "alert-004",
                machine_id: "M-001",
                chc_id: "chc-001",
                alert_type: "fuel_low",
                severity: "medium",
                status: "open",
                message: "Fuel level low",
                description: "M-001 fuel level is below 30%",
            },
            {
                id: "alert-005",
                machine_id: "M-003",
                chc_id: "chc-002",
                alert_type: "anomaly",
                severity: "low",
                status: "acknowledged",
                message: "Performance anomaly detected",
                description: "Fuel efficiency decreased by 15%",
            },
            {
                id: "alert-006",
                machine_id: "M-009",
                chc_id: "chc-006",
                alert_type: "maintenance",
                severity: "high",
                status: "open",
                message: "Scheduled maintenance pending",
                description: "M-009 maintenance schedule overdue by 5 days",
            },
            {
                id: "alert-007",
                machine_id: "M-011",
                chc_id: "chc-008",
                alert_type: "underutilization",
                severity: "medium",
                status: "open",
                message: "Low utilization rate",
                description: "M-011 utilization below target threshold",
            },
            {
                id: "alert-008",
                machine_id: "M-004",
                chc_id: "chc-003",
                alert_type: "offline",
                severity: "critical",
                status: "open",
                message: "Machine offline - Maintenance Mode",
                description: "M-004 is currently in maintenance, expected back in 3 days",
            },
            {
                id: "alert-009",
                machine_id: "M-012",
                chc_id: "chc-001",
                alert_type: "fuel_low",
                severity: "medium",
                status: "open",
                message: "Fuel tank low",
                description: "M-012 fuel level 30%, refuel recommended",
            },
            {
                id: "alert-010",
                machine_id: "M-014",
                chc_id: "chc-006",
                alert_type: "anomaly",
                severity: "low",
                status: "acknowledged",
                message: "Engine temperature fluctuation",
                description: "M-014 showing temperature variations - monitoring required",
            },
            {
                id: "alert-011",
                machine_id: "M-007",
                chc_id: "chc-001",
                alert_type: "offline",
                severity: "critical",
                status: "open",
                message: "Machine offline - No recent activity",
                description: "M-007 offline for 25 days, requires inspection",
            },
            {
                id: "alert-012",
                machine_id: "M-015",
                chc_id: "chc-007",
                alert_type: "maintenance",
                severity: "medium",
                status: "open",
                message: "Filter replacement due",
                description: "M-015 filter replacement recommended",
            },
            {
                id: "alert-013",
                machine_id: "M-010",
                chc_id: "chc-007",
                alert_type: "underutilization",
                severity: "low",
                status: "acknowledged",
                message: "Moderate utilization",
                description: "M-010 utilization rate at 81% - within acceptable range",
            },
            {
                id: "alert-014",
                machine_id: "M-016",
                chc_id: "chc-008",
                alert_type: "anomaly",
                severity: "low",
                status: "open",
                message: "Fuel consumption higher than normal",
                description: "M-016 fuel efficiency 6.9 km/l - below average",
            },
            {
                id: "alert-015",
                machine_id: "M-013",
                chc_id: "chc-002",
                alert_type: "fuel_low",
                severity: "high",
                status: "open",
                message: "Critical fuel level",
                description: "M-013 fuel level at 25% - urgent refueling needed",
            },
        ],
        skipDuplicates: true,
    })
    console.log(`✅ Created ${alerts.count} Alerts`)

    // 7. Create Machine Positions
    console.log("📍 Creating Machine Positions...")
    const positions = await prisma.machinePosition.createMany({
        data: [
            {
                id: "pos-001",
                machine_id: "M-001",
                latitude: 29.1833,
                longitude: 75.7597,
                speed: 25.5,
                heading: 180,
                timestamp: new Date(now.getTime() - 5 * 60 * 1000),
            },
            {
                id: "pos-002",
                machine_id: "M-003",
                latitude: 30.9046,
                longitude: 75.8569,
                speed: 35.2,
                heading: 90,
                timestamp: new Date(now.getTime() - 3 * 60 * 1000),
            },
            {
                id: "pos-003",
                machine_id: "M-005",
                latitude: 22.7196,
                longitude: 75.8577,
                speed: 15.8,
                heading: 270,
                timestamp: new Date(now.getTime() - 2 * 60 * 1000),
            },
            {
                id: "pos-004",
                machine_id: "M-006",
                latitude: 26.9046,
                longitude: 75.8569,
                speed: 20.0,
                heading: 45,
                timestamp: new Date(),
            },
            {
                id: "pos-005",
                machine_id: "M-009",
                latitude: 12.9716,
                longitude: 77.5946,
                speed: 30.2,
                heading: 225,
                timestamp: new Date(now.getTime() - 4 * 60 * 1000),
            },
            {
                id: "pos-006",
                machine_id: "M-010",
                latitude: 13.0827,
                longitude: 80.2707,
                speed: 22.5,
                heading: 135,
                timestamp: new Date(now.getTime() - 1 * 60 * 1000),
            },
            {
                id: "pos-007",
                machine_id: "M-011",
                latitude: 23.0225,
                longitude: 72.5714,
                speed: 28.0,
                heading: 0,
                timestamp: new Date(now.getTime() - 6 * 60 * 1000),
            },
            {
                id: "pos-008",
                machine_id: "M-013",
                latitude: 30.92,
                longitude: 75.88,
                speed: 26.5,
                heading: 315,
                timestamp: new Date(now.getTime() - 7 * 60 * 1000),
            },
            {
                id: "pos-009",
                machine_id: "M-014",
                latitude: 12.98,
                longitude: 77.6,
                speed: 32.0,
                heading: 45,
                timestamp: new Date(now.getTime() - 2 * 60 * 1000),
            },
            {
                id: "pos-010",
                machine_id: "M-015",
                latitude: 13.05,
                longitude: 80.3,
                speed: 24.5,
                heading: 180,
                timestamp: new Date(now.getTime() - 8 * 60 * 1000),
            },
            {
                id: "pos-011",
                machine_id: "M-016",
                latitude: 23.05,
                longitude: 72.58,
                speed: 33.8,
                heading: 90,
                timestamp: new Date(now.getTime() - 3 * 60 * 1000),
            },
        ],
        skipDuplicates: true,
    })
    console.log(`✅ Created ${positions.count} Machine Positions`)

    console.log("\n✨ Database seeding completed successfully!")
    console.log("📊 Summary:")
    console.log(`  • CHCs: ${chcs.count}`)
    console.log(`  • Operators: ${operators.count}`)
    console.log(`  • Machines: ${machines.count}`)
    console.log(`  • Usage Logs: ${usageLogs.count}`)
    console.log(`  • Maintenance Records: ${maintenanceRecords.count}`)
    console.log(`  • Alerts: ${alerts.count}`)
    console.log(`  • Machine Positions: ${positions.count}`)
}

main()
    .catch((e) => {
        console.error("❌ Error during seeding:", e)
        process.exit(1)
    })
    .finally(async () => {
        await prisma.$disconnect()
    })
